version: '3.8'

services:
  backend:
    build: 
      context: ./MrChef-Backend
      dockerfile: Dockerfile
    container_name: mrchef-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/mrchef
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Freya-100MTH
      - MYSQL_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: 
      context: ./MrChef-FrontEnd
      dockerfile: Dockerfile
    container_name: mrchef-frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  dependency-check-data: